services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - discordToken=${discordToken}
      - telegramToken=${telegramToken}
  postgres:
    image: "postgres:12.19-alpine"
    environment:
      - DATABASE_URL=${DATABASE_URL}
