app = "russianloses"
primary_region = "waw"


[build]
dockerfile = "fly.Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
